version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DB_URL=jdbc:mysql://mysql:3306/spring_product_crud_db
      - DB_USER=root
      - DB_PASS=dodgedart79

  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=spring_product_crud_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=dodgedart79
      - MYSQL_ROOT_PASSWORD=dodgedart79
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
