version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dodgedart79
      MYSQL_DATABASE: spring_product_crud_db
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_URL: jdbc:mysql://mysql-db:3306/spring_product_crud_db
      DB_USER: root
      DB_PASS: dodgedart79

volumes:
  mysql-data:
